//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ProxyHttpCar {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Car", Namespace="http://carservice/Employee")]
    [System.SerializableAttribute()]
    public partial class Car : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegNrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrandField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string YearModelField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegNr {
            get {
                return this.RegNrField;
            }
            set {
                if ((object.ReferenceEquals(this.RegNrField, value) != true)) {
                    this.RegNrField = value;
                    this.RaisePropertyChanged("RegNr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Color {
            get {
                return this.ColorField;
            }
            set {
                if ((object.ReferenceEquals(this.ColorField, value) != true)) {
                    this.ColorField = value;
                    this.RaisePropertyChanged("Color");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Brand {
            get {
                return this.BrandField;
            }
            set {
                if ((object.ReferenceEquals(this.BrandField, value) != true)) {
                    this.BrandField = value;
                    this.RaisePropertyChanged("Brand");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string YearModel {
            get {
                return this.YearModelField;
            }
            set {
                if ((object.ReferenceEquals(this.YearModelField, value) != true)) {
                    this.YearModelField = value;
                    this.RaisePropertyChanged("YearModel");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://schemas.datacontract.org/2004/07/Data.Domains")]
    [System.SerializableAttribute()]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FName {
            get {
                return this.FNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FNameField, value) != true)) {
                    this.FNameField = value;
                    this.RaisePropertyChanged("FName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LName {
            get {
                return this.LNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LNameField, value) != true)) {
                    this.LNameField = value;
                    this.RaisePropertyChanged("LName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Booking", Namespace="http://schemas.datacontract.org/2004/07/Data.Domains")]
    [System.SerializableAttribute()]
    public partial class Booking : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CarIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustumerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ReturnedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CarId {
            get {
                return this.CarIdField;
            }
            set {
                if ((this.CarIdField.Equals(value) != true)) {
                    this.CarIdField = value;
                    this.RaisePropertyChanged("CarId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustumerId {
            get {
                return this.CustumerIdField;
            }
            set {
                if ((this.CustumerIdField.Equals(value) != true)) {
                    this.CustumerIdField = value;
                    this.RaisePropertyChanged("CustumerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime End {
            get {
                return this.EndField;
            }
            set {
                if ((this.EndField.Equals(value) != true)) {
                    this.EndField = value;
                    this.RaisePropertyChanged("End");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Returned {
            get {
                return this.ReturnedField;
            }
            set {
                if ((this.ReturnedField.Equals(value) != true)) {
                    this.ReturnedField = value;
                    this.RaisePropertyChanged("Returned");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Start {
            get {
                return this.StartField;
            }
            set {
                if ((this.StartField.Equals(value) != true)) {
                    this.StartField = value;
                    this.RaisePropertyChanged("Start");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyHttpCar.IServiceCar")]
    public interface IServiceCar {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGenericOf_Car/Create", ReplyAction="http://tempuri.org/IServiceGenericOf_Car/CreateResponse")]
        void Create(Client.ProxyHttpCar.Car entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGenericOf_Car/Create", ReplyAction="http://tempuri.org/IServiceGenericOf_Car/CreateResponse")]
        System.Threading.Tasks.Task CreateAsync(Client.ProxyHttpCar.Car entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGenericOf_Car/ReadAll", ReplyAction="http://tempuri.org/IServiceGenericOf_Car/ReadAllResponse")]
        Client.ProxyHttpCar.Car[] ReadAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGenericOf_Car/ReadAll", ReplyAction="http://tempuri.org/IServiceGenericOf_Car/ReadAllResponse")]
        System.Threading.Tasks.Task<Client.ProxyHttpCar.Car[]> ReadAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGenericOf_Car/ReadById", ReplyAction="http://tempuri.org/IServiceGenericOf_Car/ReadByIdResponse")]
        Client.ProxyHttpCar.Car ReadById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGenericOf_Car/ReadById", ReplyAction="http://tempuri.org/IServiceGenericOf_Car/ReadByIdResponse")]
        System.Threading.Tasks.Task<Client.ProxyHttpCar.Car> ReadByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGenericOf_Car/Update", ReplyAction="http://tempuri.org/IServiceGenericOf_Car/UpdateResponse")]
        void Update(Client.ProxyHttpCar.Car entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGenericOf_Car/Update", ReplyAction="http://tempuri.org/IServiceGenericOf_Car/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(Client.ProxyHttpCar.Car entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGenericOf_Car/Delete", ReplyAction="http://tempuri.org/IServiceGenericOf_Car/DeleteResponse")]
        void Delete(Client.ProxyHttpCar.Car entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGenericOf_Car/Delete", ReplyAction="http://tempuri.org/IServiceGenericOf_Car/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(Client.ProxyHttpCar.Car entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCar/ReadCurrentCustomer", ReplyAction="http://tempuri.org/IServiceCar/ReadCurrentCustomerResponse")]
        Client.ProxyHttpCar.Customer ReadCurrentCustomer(Client.ProxyHttpCar.Car entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCar/ReadCurrentCustomer", ReplyAction="http://tempuri.org/IServiceCar/ReadCurrentCustomerResponse")]
        System.Threading.Tasks.Task<Client.ProxyHttpCar.Customer> ReadCurrentCustomerAsync(Client.ProxyHttpCar.Car entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCar/ReadAllPastCustomers", ReplyAction="http://tempuri.org/IServiceCar/ReadAllPastCustomersResponse")]
        Client.ProxyHttpCar.Customer[] ReadAllPastCustomers(Client.ProxyHttpCar.Car entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCar/ReadAllPastCustomers", ReplyAction="http://tempuri.org/IServiceCar/ReadAllPastCustomersResponse")]
        System.Threading.Tasks.Task<Client.ProxyHttpCar.Customer[]> ReadAllPastCustomersAsync(Client.ProxyHttpCar.Car entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCar/ReadCurrentBooking", ReplyAction="http://tempuri.org/IServiceCar/ReadCurrentBookingResponse")]
        Client.ProxyHttpCar.Booking ReadCurrentBooking(Client.ProxyHttpCar.Car entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCar/ReadCurrentBooking", ReplyAction="http://tempuri.org/IServiceCar/ReadCurrentBookingResponse")]
        System.Threading.Tasks.Task<Client.ProxyHttpCar.Booking> ReadCurrentBookingAsync(Client.ProxyHttpCar.Car entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCar/ReadAllPastBookings", ReplyAction="http://tempuri.org/IServiceCar/ReadAllPastBookingsResponse")]
        Client.ProxyHttpCar.Booking[] ReadAllPastBookings(Client.ProxyHttpCar.Car entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCar/ReadAllPastBookings", ReplyAction="http://tempuri.org/IServiceCar/ReadAllPastBookingsResponse")]
        System.Threading.Tasks.Task<Client.ProxyHttpCar.Booking[]> ReadAllPastBookingsAsync(Client.ProxyHttpCar.Car entity);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceCarChannel : Client.ProxyHttpCar.IServiceCar, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceCarClient : System.ServiceModel.ClientBase<Client.ProxyHttpCar.IServiceCar>, Client.ProxyHttpCar.IServiceCar {
        
        public ServiceCarClient() {
        }
        
        public ServiceCarClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceCarClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceCarClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceCarClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Create(Client.ProxyHttpCar.Car entity) {
            base.Channel.Create(entity);
        }
        
        public System.Threading.Tasks.Task CreateAsync(Client.ProxyHttpCar.Car entity) {
            return base.Channel.CreateAsync(entity);
        }
        
        public Client.ProxyHttpCar.Car[] ReadAll() {
            return base.Channel.ReadAll();
        }
        
        public System.Threading.Tasks.Task<Client.ProxyHttpCar.Car[]> ReadAllAsync() {
            return base.Channel.ReadAllAsync();
        }
        
        public Client.ProxyHttpCar.Car ReadById(int id) {
            return base.Channel.ReadById(id);
        }
        
        public System.Threading.Tasks.Task<Client.ProxyHttpCar.Car> ReadByIdAsync(int id) {
            return base.Channel.ReadByIdAsync(id);
        }
        
        public void Update(Client.ProxyHttpCar.Car entity) {
            base.Channel.Update(entity);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(Client.ProxyHttpCar.Car entity) {
            return base.Channel.UpdateAsync(entity);
        }
        
        public void Delete(Client.ProxyHttpCar.Car entity) {
            base.Channel.Delete(entity);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(Client.ProxyHttpCar.Car entity) {
            return base.Channel.DeleteAsync(entity);
        }
        
        public Client.ProxyHttpCar.Customer ReadCurrentCustomer(Client.ProxyHttpCar.Car entity) {
            return base.Channel.ReadCurrentCustomer(entity);
        }
        
        public System.Threading.Tasks.Task<Client.ProxyHttpCar.Customer> ReadCurrentCustomerAsync(Client.ProxyHttpCar.Car entity) {
            return base.Channel.ReadCurrentCustomerAsync(entity);
        }
        
        public Client.ProxyHttpCar.Customer[] ReadAllPastCustomers(Client.ProxyHttpCar.Car entity) {
            return base.Channel.ReadAllPastCustomers(entity);
        }
        
        public System.Threading.Tasks.Task<Client.ProxyHttpCar.Customer[]> ReadAllPastCustomersAsync(Client.ProxyHttpCar.Car entity) {
            return base.Channel.ReadAllPastCustomersAsync(entity);
        }
        
        public Client.ProxyHttpCar.Booking ReadCurrentBooking(Client.ProxyHttpCar.Car entity) {
            return base.Channel.ReadCurrentBooking(entity);
        }
        
        public System.Threading.Tasks.Task<Client.ProxyHttpCar.Booking> ReadCurrentBookingAsync(Client.ProxyHttpCar.Car entity) {
            return base.Channel.ReadCurrentBookingAsync(entity);
        }
        
        public Client.ProxyHttpCar.Booking[] ReadAllPastBookings(Client.ProxyHttpCar.Car entity) {
            return base.Channel.ReadAllPastBookings(entity);
        }
        
        public System.Threading.Tasks.Task<Client.ProxyHttpCar.Booking[]> ReadAllPastBookingsAsync(Client.ProxyHttpCar.Car entity) {
            return base.Channel.ReadAllPastBookingsAsync(entity);
        }
    }
}
